services:
  cli:
    image: ${DESKTOP_PLUGIN_IMAGE}
    ports:
      - "8130:8080"
    privileged: true
    restart: always
    deploy: 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
